CREATE TABLE media_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT DEFAULT NULL,
  speaker VARCHAR(120) DEFAULT NULL,
  series VARCHAR(120) DEFAULT NULL,
  media_type VARCHAR(20) NOT NULL,
  source_url VARCHAR(500) NOT NULL,
  thumbnail_url VARCHAR(500) DEFAULT NULL,
  duration_seconds INT DEFAULT NULL,
  event_date DATE DEFAULT NULL,
  tags TEXT DEFAULT NULL,
  scope VARCHAR(20) NOT NULL DEFAULT 'zonal',
  state VARCHAR(120) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_by INT NOT NULL,
  updated_by INT DEFAULT NULL,
  published_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  INDEX media_state_idx (state),
  INDEX media_status_idx (status),
  INDEX media_event_date_idx (event_date),
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE publication_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT DEFAULT NULL,
  publication_type VARCHAR(60) NOT NULL,
  file_url VARCHAR(500) NOT NULL,
  cover_image_url VARCHAR(500) DEFAULT NULL,
  publish_date DATE DEFAULT NULL,
  tags TEXT DEFAULT NULL,
  scope VARCHAR(20) NOT NULL DEFAULT 'zonal',
  state VARCHAR(120) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_by INT NOT NULL,
  updated_by INT DEFAULT NULL,
  published_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  INDEX publication_state_idx (state),
  INDEX publication_status_idx (status),
  INDEX publication_date_idx (publish_date),
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (updated_by) REFERENCES users(id)
);
