CREATE TABLE IF NOT EXISTS giving_campaigns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(220) DEFAULT NULL,
  summary TEXT DEFAULT NULL,
  description_html LONGTEXT DEFAULT NULL,
  campaign_type VARCHAR(60) NOT NULL,
  cover_image_url VARCHAR(500) DEFAULT NULL,
  target_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_raised DECIMAL(12,2) NOT NULL DEFAULT 0,
  beneficiary_name VARCHAR(180) DEFAULT NULL,
  payment_details TEXT DEFAULT NULL,
  deadline DATE DEFAULT NULL,
  is_urgent TINYINT(1) NOT NULL DEFAULT 0,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  scope VARCHAR(20) NOT NULL DEFAULT 'zonal',
  state VARCHAR(120) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_by INT NOT NULL,
  updated_by INT DEFAULT NULL,
  published_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  INDEX giving_scope_idx (scope),
  INDEX giving_state_idx (state),
  INDEX giving_status_idx (status),
  INDEX giving_deadline_idx (deadline),
  INDEX giving_urgent_idx (is_urgent),
  INDEX giving_featured_idx (is_featured),
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (updated_by) REFERENCES users(id)
);
