CREATE TABLE IF NOT EXISTS media_assets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(220) DEFAULT NULL,
  original_filename VARCHAR(255) DEFAULT NULL,
  stored_filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_ext VARCHAR(20) DEFAULT NULL,
  file_type VARCHAR(20) NOT NULL DEFAULT 'other',
  file_size BIGINT NOT NULL DEFAULT 0,
  folder VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  scope VARCHAR(20) NOT NULL DEFAULT 'zonal',
  state VARCHAR(120) DEFAULT NULL,
  usage_context VARCHAR(80) DEFAULT NULL,
  alt_text VARCHAR(255) DEFAULT NULL,
  caption TEXT DEFAULT NULL,
  description TEXT DEFAULT NULL,
  uploaded_by INT DEFAULT NULL,
  uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  archived_at DATETIME DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by INT DEFAULT NULL,
  updated_at DATETIME DEFAULT NULL,
  INDEX media_assets_scope_idx (scope),
  INDEX media_assets_state_idx (state),
  INDEX media_assets_type_idx (file_type),
  INDEX media_assets_status_idx (status),
  INDEX media_assets_uploaded_by_idx (uploaded_by),
  INDEX media_assets_uploaded_at_idx (uploaded_at),
  FOREIGN KEY (uploaded_by) REFERENCES users(id),
  FOREIGN KEY (deleted_by) REFERENCES users(id)
);
