INSERT IGNORE INTO states (name, slug, created_at, updated_at) VALUES
  ('Ekiti State (South)', 'ekiti-state-south', NOW(), NOW()),
  ('Ekiti State (North)', 'ekiti-state-north', NOW(), NOW()),
  ('Kwara State', 'kwara-state', NOW(), NOW()),
  ('Ogun State (Central)', 'ogun-state-central', NOW(), NOW()),
  ('Ogun State (East)', 'ogun-state-east', NOW(), NOW()),
  ('Ogun State (West)', 'ogun-state-west', NOW(), NOW()),
  ('Ondo State (North)', 'ondo-state-north', NOW(), NOW()),
  ('Ondo State (South)', 'ondo-state-south', NOW(), NOW()),
  ('Osun State 1', 'osun-state-1', NOW(), NOW()),
  ('Osun State 2', 'osun-state-2', NOW(), NOW()),
  ('Oyo State (Central)', 'oyo-state-central', NOW(), NOW()),
  ('Oyo State (North)', 'oyo-state-north', NOW(), NOW()),
  ('Oyo State (South)', 'oyo-state-south', NOW(), NOW());

INSERT IGNORE INTO regions (state_name, name, created_at, updated_at) VALUES
  ('Ekiti State (North)', 'Aramoko', NOW(), NOW()),
  ('Ekiti State (North)', 'Ido', NOW(), NOW()),
  ('Ekiti State (North)', 'Ikole', NOW(), NOW()),
  ('Ekiti State (North)', 'Oye', NOW(), NOW()),
  ('Ekiti State (North)', 'Others', NOW(), NOW()),
  ('Ekiti State (South)', 'Ado', NOW(), NOW()),
  ('Ekiti State (South)', 'Ilawe', NOW(), NOW()),
  ('Ekiti State (South)', 'Ikere', NOW(), NOW()),
  ('Ekiti State (South)', 'Omuo', NOW(), NOW()),
  ('Ekiti State (South)', 'Others', NOW(), NOW()),
  ('Kwara State', 'Ganmo', NOW(), NOW()),
  ('Kwara State', 'Gbugbu', NOW(), NOW()),
  ('Kwara State', 'Ilorin', NOW(), NOW()),
  ('Kwara State', 'Offa', NOW(), NOW()),
  ('Kwara State', 'Omu-Aran', NOW(), NOW()),
  ('Kwara State', 'Oro', NOW(), NOW()),
  ('Kwara State', 'Edu', NOW(), NOW()),
  ('Kwara State', 'Others', NOW(), NOW()),
  ('Ogun State (Central)', 'Abeokuta', NOW(), NOW()),
  ('Ogun State (Central)', 'Ayetoro', NOW(), NOW()),
  ('Ogun State (Central)', 'Ifo', NOW(), NOW()),
  ('Ogun State (Central)', 'Itori', NOW(), NOW()),
  ('Ogun State (Central)', 'Odeda', NOW(), NOW()),
  ('Ogun State (Central)', 'Oke-Ogun', NOW(), NOW()),
  ('Ogun State (Central)', 'Papa', NOW(), NOW()),
  ('Ogun State (Central)', 'Others', NOW(), NOW()),
  ('Ogun State (East)', 'Ajuwon', NOW(), NOW()),
  ('Ogun State (East)', 'Sagamu', NOW(), NOW()),
  ('Ogun State (East)', 'Ijebu Ife', NOW(), NOW()),
  ('Ogun State (East)', 'Owode', NOW(), NOW()),
  ('Ogun State (East)', 'Waterside', NOW(), NOW()),
  ('Ogun State (East)', 'Ogijo', NOW(), NOW()),
  ('Ogun State (East)', 'Iperu', NOW(), NOW()),
  ('Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
  ('Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
  ('Ogun State (West)', 'Ota', NOW(), NOW()),
  ('Ogun State (West)', 'Yewa', NOW(), NOW()),
  ('Ogun State (West)', 'Ilogbo', NOW(), NOW()),
  ('Ogun State (West)', 'Lusada', NOW(), NOW()),
  ('Ogun State (West)', 'Remo', NOW(), NOW()),
  ('Ondo State (North)', 'Akure', NOW(), NOW()),
  ('Ondo State (North)', 'Akure North', NOW(), NOW()),
  ('Ondo State (North)', 'Oka', NOW(), NOW()),
  ('Ondo State (North)', 'Ikare Akoko', NOW(), NOW()),
  ('Ondo State (North)', 'Owo', NOW(), NOW()),
  ('Ondo State (South)', 'Ondo', NOW(), NOW()),
  ('Ondo State (South)', 'Okitipupa', NOW(), NOW()),
  ('Ondo State (South)', 'Ile Oluji', NOW(), NOW()),
  ('Osun State 2', 'Ife', NOW(), NOW()),
  ('Osun State 2', 'Irewole', NOW(), NOW()),
  ('Osun State 2', 'Ishasha (Ife North)', NOW(), NOW()),
  ('Osun State 2', 'Ife South', NOW(), NOW()),
  ('Osun State 2', 'Oriade', NOW(), NOW()),
  ('Osun State 2', 'Ilesha', NOW(), NOW()),
  ('Osun State 2', 'Others', NOW(), NOW()),
  ('Oyo State (Central)', 'Egbeda', NOW(), NOW()),
  ('Oyo State (Central)', 'Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Oluyole', NOW(), NOW()),
  ('Oyo State (Central)', 'Ido', NOW(), NOW()),
  ('Oyo State (Central)', 'Akinyele', NOW(), NOW()),
  ('Oyo State (North)', 'Irepo', NOW(), NOW()),
  ('Oyo State (North)', 'Saki', NOW(), NOW()),
  ('Oyo State (North)', 'Iseyin', NOW(), NOW()),
  ('Oyo State (North)', 'Ibarapa', NOW(), NOW()),
  ('Oyo State (North)', 'Kajola', NOW(), NOW()),
  ('Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo', NOW(), NOW()),
  ('Oyo State (South)', 'Afijio', NOW(), NOW()),
  ('Oyo State (South)', 'Orile', NOW(), NOW()),
  ('Oyo State (South)', 'Surulere', NOW(), NOW());
