INSERT IGNORE INTO institutions (state_name, name, created_at, updated_at) VALUES
  ('Ekiti State (North)', 'Others', NOW(), NOW()),
  ('Ekiti State (North)', 'Afe Babalola University, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'College Of Education, Ikere Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'College Of Health Sciences And Technology, Ijero', NOW(), NOW()),
  ('Ekiti State (North)', 'College Of Health Technology, Orin', NOW(), NOW()),
  ('Ekiti State (North)', 'Crown Polytechnic, Odo Ilawe', NOW(), NOW()),
  ('Ekiti State (North)', 'Ekiti State University, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'Federal University of Technology and Environmental Science, Iyin Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'Federal Polytechnic, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'Federal University, Oye Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'Institute Of Science Laboratory Technology, Ifaki', NOW(), NOW()),
  ('Ekiti State (North)', 'National Open University of Nigeria (ALL CAMPUSES IN EKITI STATE)', NOW(), NOW()),
  ('Ekiti State (North)', 'School Of Nursing and Midwifery , Ido Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'School Of Nursing, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'Bamidele Olumilua University of Science and Technology, Ikere Ekiti (BOUESI)', NOW(), NOW()),
  ('Ekiti State (North)', 'Federal College of Education, Ilawe Ekiti', NOW(), NOW()),
  ('Ekiti State (North)', 'FABOTAS College of Health Technology, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'Others', NOW(), NOW()),
  ('Ekiti State (South)', 'Afe Babalola University, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'College Of Education, Ikere Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'College Of Health Sciences And Technology, Ijero', NOW(), NOW()),
  ('Ekiti State (South)', 'College Of Health Technology, Orin', NOW(), NOW()),
  ('Ekiti State (South)', 'Crown Polytechnic, Odo Ilawe', NOW(), NOW()),
  ('Ekiti State (South)', 'Ekiti State University, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'Federal University of Technology and Environmental Science, Iyin Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'Federal Polytechnic, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'Federal University, Oye Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'Institute Of Science Laboratory Technology, Ifaki', NOW(), NOW()),
  ('Ekiti State (South)', 'National Open University of Nigeria (ALL CAMPUSES IN EKITI STATE)', NOW(), NOW()),
  ('Ekiti State (South)', 'School Of Nursing and Midwifery , Ido Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'School Of Nursing, Ado Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'Bamidele Olumilua University of Science and Technology, Ikere Ekiti (BOUESI)', NOW(), NOW()),
  ('Ekiti State (South)', 'Federal College of Education, Ilawe Ekiti', NOW(), NOW()),
  ('Ekiti State (South)', 'FABOTAS College of Health Technology, Ado Ekiti', NOW(), NOW()),
  ('Kwara State', 'Others NOT Listed', NOW(), NOW()),
  ('Kwara State', 'Alkimah University, Ilorin', NOW(), NOW()),
  ('Kwara State', 'College Of Education Technical, Lafiagi', NOW(), NOW()),
  ('Kwara State', 'College Of Education, Oro', NOW(), NOW()),
  ('Kwara State', 'Federal Training Centre (FTC), Ilorin', NOW(), NOW()),
  ('Kwara State', 'Institute Of Technology, Ilorin', NOW(), NOW()),
  ('Kwara State', 'Kwara State Polytechnic, Ilorin', NOW(), NOW()),
  ('Kwara State', 'Kwara State College Of Education, Offa', NOW(), NOW()),
  ('Kwara State', 'Kwara State University, Malete', NOW(), NOW()),
  ('Kwara State', 'Landmark University, Omu - Aran', NOW(), NOW()),
  ('Kwara State', 'National Open University of Nigeria (ALL CAMPUSES IN KWARA STATE)', NOW(), NOW()),
  ('Kwara State', 'School Of Health Information, Ilorin', NOW(), NOW()),
  ('Kwara State', 'School Of Midwifery, Ilorin', NOW(), NOW()),
  ('Kwara State', 'School Of Nursing, Ilorin West', NOW(), NOW()),
  ('Kwara State', 'Staff Development Centre, Ilorin', NOW(), NOW()),
  ('Kwara State', 'University Of Ilorin - College of Health sciences, Ilorin', NOW(), NOW()),
  ('Kwara State', 'University of Ilorin - Mini campus, Ilorin', NOW(), NOW()),
  ('Kwara State', 'University of Ilorin - UITH, Ilorin', NOW(), NOW()),
  ('Kwara State', 'University of Ilorin- Permanent Site, Ilorin', NOW(), NOW()),
  ('Kwara State', 'University School Of Prelimenary Studies, Ilorin', NOW(), NOW()),
  ('Kwara State', 'Metropolitan Polytechnic Offa', NOW(), NOW()),
  ('Kwara State', 'Summit University, Offa(Ansaudeen)', NOW(), NOW()),
  ('Kwara State', 'Pan African College of Education Offa', NOW(), NOW()),
  ('Kwara State', 'Lens Polytechnics, Offa', NOW(), NOW()),
  ('Kwara State', 'College of Health Technology Offa', NOW(), NOW()),
  ('Kwara State', 'College of Education Ilemona', NOW(), NOW()),
  ('Kwara State', 'Federal Poly Offa', NOW(), NOW()),
  ('Kwara State', 'Unilorin College of Health Sciences, Ilorin East', NOW(), NOW()),
  ('Kwara State', 'College of Education, Ilorin West', NOW(), NOW()),
  ('Ogun State (Central)', 'Others (if your school is not listed)', NOW(), NOW()),
  ('Ogun State (Central)', 'Abraham Adesanya polytechnic oru', NOW(), NOW()),
  ('Ogun State (Central)', 'All over central polytechnic', NOW(), NOW()),
  ('Ogun State (Central)', 'Babcock University, Ilisan', NOW(), NOW()),
  ('Ogun State (Central)', 'College of Health Technology Ilese', NOW(), NOW()),
  ('Ogun State (Central)', 'Covenant University', NOW(), NOW()),
  ('Ogun State (Central)', 'Federal College of Education, Osiele', NOW(), NOW()),
  ('Ogun State (Central)', 'Federal Polytechnic Ilaro', NOW(), NOW()),
  ('Ogun State (Central)', 'Federal University of Agriculture, Abiokuta', NOW(), NOW()),
  ('Ogun State (Central)', 'Gateway polytechnic Itori', NOW(), NOW()),
  ('Ogun State (Central)', 'LUTH extension', NOW(), NOW()),
  ('Ogun State (Central)', 'Mcphersons University, Ajebo', NOW(), NOW()),
  ('Ogun State (Central)', 'Moshood Abiola polytechnic, Ojere', NOW(), NOW()),
  ('Ogun State (Central)', 'National Open University of Nigeria (ALL CAMPUSES IN OGUN STATE)', NOW(), NOW()),
  ('Ogun State (Central)', 'Ogun State University, Sapade', NOW(), NOW()),
  ('Ogun State (Central)', 'Olabisi Onabanjo University study centre Ososa', NOW(), NOW()),
  ('Ogun State (Central)', 'Olabisi Onabanjo teaching Hospital', NOW(), NOW()),
  ('Ogun State (Central)', 'Olabisi Onabanjo university', NOW(), NOW()),
  ('Ogun State (Central)', 'Olabisi Onabanjo University, Ikene', NOW(), NOW()),
  ('Ogun State (Central)', 'Olabisi Onabanjo University, school of Engineering', NOW(), NOW()),
  ('Ogun State (Central)', 'Olabisi OnabanjoUuniversity, College of Agriculture', NOW(), NOW()),
  ('Ogun State (Central)', 'Redeemers University', NOW(), NOW()),
  ('Ogun State (Central)', 'School of Nursing Idi Aba', NOW(), NOW()),
  ('Ogun State (Central)', 'School of nursing Ilaro', NOW(), NOW()),
  ('Ogun State (Central)', 'School of Nursing lantoro', NOW(), NOW()),
  ('Ogun State (Central)', 'School of Psychiatric Nursing, Aro', NOW(), NOW()),
  ('Ogun State (Central)', 'Tai Solarin college of Education, Omu', NOW(), NOW()),
  ('Ogun State (Central)', 'Tai Solarin University of Education, Ijagun', NOW(), NOW()),
  ('Ogun State (Central)', 'The Bells University', NOW(), NOW()),
  ('Ogun State (Central)', 'Yewa college of Education, Idagba', NOW(), NOW()),
  ('Ogun State (Central)', 'Grace Polytechnics', NOW(), NOW()),
  ('Ogun State (Central)', 'TASCE, Ijebu Region', NOW(), NOW()),
  ('Ogun State (Central)', 'Bells University of Technology, Ilogbo Region', NOW(), NOW()),
  ('Ogun State (Central)', 'All-Over Central Polytechnics, Ilogbo Region', NOW(), NOW()),
  ('Ogun State (Central)', 'Awori College of Education', NOW(), NOW()),
  ('Ogun State (Central)', 'Yewa Central College, Ayetoro', NOW(), NOW()),
  ('Ogun State (Central)', 'OOU College of Agric, Ayetoro', NOW(), NOW()),
  ('Ogun State (Central)', 'OOUTH, Sagamu', NOW(), NOW()),
  ('Ogun State (Central)', 'Ogun State Intitute of Technology (OGITECH), Igbesa, Lusada', NOW(), NOW()),
  ('Ogun State (Central)', 'Gateway Poly Remo Region', NOW(), NOW()),
  ('Ogun State (East)', 'Others (if your school is not listed)', NOW(), NOW()),
  ('Ogun State (East)', 'Abraham Adesanya polytechnic oru', NOW(), NOW()),
  ('Ogun State (East)', 'All over central polytechnic', NOW(), NOW()),
  ('Ogun State (East)', 'Babcock University, Ilisan', NOW(), NOW()),
  ('Ogun State (East)', 'College of Health Technology Ilese', NOW(), NOW()),
  ('Ogun State (East)', 'Covenant University', NOW(), NOW()),
  ('Ogun State (East)', 'Federal College of Education, Osiele', NOW(), NOW()),
  ('Ogun State (East)', 'Federal Polytechnic Ilaro', NOW(), NOW()),
  ('Ogun State (East)', 'Federal University of Agriculture, Abiokuta', NOW(), NOW()),
  ('Ogun State (East)', 'Gateway polytechnic Itori', NOW(), NOW()),
  ('Ogun State (East)', 'LUTH extension', NOW(), NOW()),
  ('Ogun State (East)', 'Mcphersons University, Ajebo', NOW(), NOW()),
  ('Ogun State (East)', 'Moshood Abiola polytechnic, Ojere', NOW(), NOW()),
  ('Ogun State (East)', 'National Open University of Nigeria (ALL CAMPUSES IN OGUN STATE)', NOW(), NOW()),
  ('Ogun State (East)', 'Ogun State University, Sapade', NOW(), NOW()),
  ('Ogun State (East)', 'Olabisi Onabanjo University study centre Ososa', NOW(), NOW()),
  ('Ogun State (East)', 'Olabisi Onabanjo teaching Hospital', NOW(), NOW()),
  ('Ogun State (East)', 'Olabisi Onabanjo university', NOW(), NOW()),
  ('Ogun State (East)', 'Olabisi Onabanjo University, Ikene', NOW(), NOW()),
  ('Ogun State (East)', 'Olabisi Onabanjo University, school of Engineering', NOW(), NOW()),
  ('Ogun State (East)', 'Olabisi OnabanjoUuniversity, College of Agriculture', NOW(), NOW()),
  ('Ogun State (East)', 'Redeemers University', NOW(), NOW()),
  ('Ogun State (East)', 'School of Nursing Idi Aba', NOW(), NOW()),
  ('Ogun State (East)', 'School of nursing Ilaro', NOW(), NOW()),
  ('Ogun State (East)', 'School of Nursing lantoro', NOW(), NOW()),
  ('Ogun State (East)', 'School of Psychiatric Nursing, Aro', NOW(), NOW()),
  ('Ogun State (East)', 'Tai Solarin college of Education, Omu', NOW(), NOW()),
  ('Ogun State (East)', 'Tai Solarin University of Education, Ijagun', NOW(), NOW()),
  ('Ogun State (East)', 'The Bells University', NOW(), NOW()),
  ('Ogun State (East)', 'Yewa college of Education, Idagba', NOW(), NOW()),
  ('Ogun State (East)', 'Grace Polytechnics', NOW(), NOW()),
  ('Ogun State (East)', 'TASCE, Ijebu Region', NOW(), NOW()),
  ('Ogun State (East)', 'Bells University of Technology, Ilogbo Region', NOW(), NOW()),
  ('Ogun State (East)', 'All-Over Central Polytechnics, Ilogbo Region', NOW(), NOW()),
  ('Ogun State (East)', 'Awori College of Education', NOW(), NOW()),
  ('Ogun State (East)', 'Yewa Central College, Ayetoro', NOW(), NOW()),
  ('Ogun State (East)', 'OOU College of Agric, Ayetoro', NOW(), NOW()),
  ('Ogun State (East)', 'OOUTH, Sagamu', NOW(), NOW()),
  ('Ogun State (East)', 'Ogun State Intitute of Technology (OGITECH), Igbesa, Lusada', NOW(), NOW()),
  ('Ogun State (East)', 'Gateway Poly Remo Region', NOW(), NOW()),
  ('Ogun State (West)', 'Others (if your school is not listed)', NOW(), NOW()),
  ('Ogun State (West)', 'Abraham Adesanya polytechnic oru', NOW(), NOW()),
  ('Ogun State (West)', 'All over central polytechnic', NOW(), NOW()),
  ('Ogun State (West)', 'Babcock University, Ilisan', NOW(), NOW()),
  ('Ogun State (West)', 'College of Health Technology Ilese', NOW(), NOW()),
  ('Ogun State (West)', 'Covenant University', NOW(), NOW()),
  ('Ogun State (West)', 'Federal College of Education, Osiele', NOW(), NOW()),
  ('Ogun State (West)', 'Federal Polytechnic Ilaro', NOW(), NOW()),
  ('Ogun State (West)', 'Federal University of Agriculture, Abiokuta', NOW(), NOW()),
  ('Ogun State (West)', 'Gateway polytechnic Itori', NOW(), NOW()),
  ('Ogun State (West)', 'LUTH extension', NOW(), NOW()),
  ('Ogun State (West)', 'Mcphersons University, Ajebo', NOW(), NOW()),
  ('Ogun State (West)', 'Moshood Abiola polytechnic, Ojere', NOW(), NOW()),
  ('Ogun State (West)', 'National Open University of Nigeria (ALL CAMPUSES IN OGUN STATE)', NOW(), NOW()),
  ('Ogun State (West)', 'Ogun State University, Sapade', NOW(), NOW()),
  ('Ogun State (West)', 'Olabisi Onabanjo University study centre Ososa', NOW(), NOW()),
  ('Ogun State (West)', 'Olabisi Onabanjo teaching Hospital', NOW(), NOW()),
  ('Ogun State (West)', 'Olabisi Onabanjo university', NOW(), NOW()),
  ('Ogun State (West)', 'Olabisi Onabanjo University, Ikene', NOW(), NOW()),
  ('Ogun State (West)', 'Olabisi Onabanjo University, school of Engineering', NOW(), NOW()),
  ('Ogun State (West)', 'Olabisi OnabanjoUuniversity, College of Agriculture', NOW(), NOW()),
  ('Ogun State (West)', 'Redeemers University', NOW(), NOW()),
  ('Ogun State (West)', 'School of Nursing Idi Aba', NOW(), NOW()),
  ('Ogun State (West)', 'School of nursing Ilaro', NOW(), NOW()),
  ('Ogun State (West)', 'School of Nursing lantoro', NOW(), NOW()),
  ('Ogun State (West)', 'School of Psychiatric Nursing, Aro', NOW(), NOW()),
  ('Ogun State (West)', 'Tai Solarin college of Education, Omu', NOW(), NOW()),
  ('Ogun State (West)', 'Tai Solarin University of Education, Ijagun', NOW(), NOW()),
  ('Ogun State (West)', 'The Bells University', NOW(), NOW()),
  ('Ogun State (West)', 'Yewa college of Education, Idagba', NOW(), NOW()),
  ('Ogun State (West)', 'Grace Polytechnics', NOW(), NOW()),
  ('Ogun State (West)', 'TASCE, Ijebu Region', NOW(), NOW()),
  ('Ogun State (West)', 'Bells University of Technology, Ilogbo Region', NOW(), NOW()),
  ('Ogun State (West)', 'All-Over Central Polytechnics, Ilogbo Region', NOW(), NOW()),
  ('Ogun State (West)', 'Awori College of Education', NOW(), NOW()),
  ('Ogun State (West)', 'Yewa Central College, Ayetoro', NOW(), NOW()),
  ('Ogun State (West)', 'OOU College of Agric, Ayetoro', NOW(), NOW()),
  ('Ogun State (West)', 'OOUTH, Sagamu', NOW(), NOW()),
  ('Ogun State (West)', 'Ogun State Intitute of Technology (OGITECH), Igbesa, Lusada', NOW(), NOW()),
  ('Ogun State (West)', 'Gateway Poly Remo Region', NOW(), NOW()),
  ('Ondo State (North)', 'Others not listed', NOW(), NOW()),
  ('Ondo State (North)', 'Achiever University, Owo', NOW(), NOW()),
  ('Ondo State (North)', 'Adekunle Ajasin University, Akungba, Akoko', NOW(), NOW()),
  ('Ondo State (North)', 'Adeyemi College Of Education, Ondo', NOW(), NOW()),
  ('Ondo State (North)', 'All State College Of Education, Ero', NOW(), NOW()),
  ('Ondo State (North)', 'Bethel College Of Education, Ijere', NOW(), NOW()),
  ('Ondo State (North)', 'Cooperative College', NOW(), NOW()),
  ('Ondo State (North)', 'Elizade University, Ilara Mokin', NOW(), NOW()),
  ('Ondo State (North)', 'Federal College Of Agriculture, Akure', NOW(), NOW()),
  ('Ondo State (North)', 'Federal University Of Technology, Akure', NOW(), NOW()),
  ('Ondo State (North)', 'Millennium College Of Health Technology', NOW(), NOW()),
  ('Ondo State (North)', 'National Open University of Nigeria (ALL CAMPUSES IN ONDO STATE)', NOW(), NOW()),
  ('Ondo State (North)', 'Ondo State University Of Medical Science, Ondo', NOW(), NOW()),
  ('Ondo State (North)', 'Rufus Giwa Polytechnic, Owo', NOW(), NOW()),
  ('Ondo State (North)', 'Rufus Giwa Polytechnic, Satellite Campus', NOW(), NOW()),
  ('Ondo State (North)', 'School Of Health Technology, Akure', NOW(), NOW()),
  ('Ondo State (North)', 'School Of Nursing And Midwifery, Akure', NOW(), NOW()),
  ('Ondo State (North)', 'Wesley University Of Science And Technology, Ondo', NOW(), NOW()),
  ('Ondo State (North)', 'Best Solution Polytechnic, Akure', NOW(), NOW()),
  ('Ondo State (North)', 'Federal Polytechnic, Ile Oluji', NOW(), NOW()),
  ('Ondo State (North)', 'Ondo State University of Science and Technology, Okitipupa', NOW(), NOW()),
  ('Ondo State (South)', 'Others not listed', NOW(), NOW()),
  ('Ondo State (South)', 'Achiever University, Owo', NOW(), NOW()),
  ('Ondo State (South)', 'Adekunle Ajasin University, Akungba, Akoko', NOW(), NOW()),
  ('Ondo State (South)', 'Adeyemi College Of Education, Ondo', NOW(), NOW()),
  ('Ondo State (South)', 'All State College Of Education, Ero', NOW(), NOW()),
  ('Ondo State (South)', 'Bethel College Of Education, Ijere', NOW(), NOW()),
  ('Ondo State (South)', 'Cooperative College', NOW(), NOW()),
  ('Ondo State (South)', 'Elizade University, Ilara Mokin', NOW(), NOW()),
  ('Ondo State (South)', 'Federal College Of Agriculture, Akure', NOW(), NOW()),
  ('Ondo State (South)', 'Federal University Of Technology, Akure', NOW(), NOW()),
  ('Ondo State (South)', 'Millennium College Of Health Technology', NOW(), NOW()),
  ('Ondo State (South)', 'National Open University of Nigeria (ALL CAMPUSES IN ONDO STATE)', NOW(), NOW()),
  ('Ondo State (South)', 'Ondo State University Of Medical Science, Ondo', NOW(), NOW()),
  ('Ondo State (South)', 'Rufus Giwa Polytechnic, Owo', NOW(), NOW()),
  ('Ondo State (South)', 'Rufus Giwa Polytechnic, Satellite Campus', NOW(), NOW()),
  ('Ondo State (South)', 'School Of Health Technology, Akure', NOW(), NOW()),
  ('Ondo State (South)', 'School Of Nursing And Midwifery, Akure', NOW(), NOW()),
  ('Ondo State (South)', 'Wesley University Of Science And Technology, Ondo', NOW(), NOW()),
  ('Ondo State (South)', 'Best Solution Polytechnic, Akure', NOW(), NOW()),
  ('Ondo State (South)', 'Federal Polytechnic, Ile Oluji', NOW(), NOW()),
  ('Ondo State (South)', 'Ondo State University of Science and Technology, Okitipupa', NOW(), NOW()),
  ('Osun State 1', 'Bowen University, Iwo', NOW(), NOW()),
  ('Osun State 1', 'Federal Polytechnic Ede', NOW(), NOW()),
  ('Osun State 1', 'Foreign Links Polytechnic, Ishasha, Ife North', NOW(), NOW()),
  ('Osun State 1', 'Ife Polytechnic', NOW(), NOW()),
  ('Osun State 1', 'Interlinks Polytechnic', NOW(), NOW()),
  ('Osun State 1', 'Joseph Ayo Babalola University', NOW(), NOW()),
  ('Osun State 1', 'Ladoke Akintola University Of Technology - TEACHING HOSPITAL, Osogbo', NOW(), NOW()),
  ('Osun State 1', 'Living Spring College of Technology, Osogbo', NOW(), NOW()),
  ('Osun State 1', 'National Open University of Nigeria (ALL CAMPUSES IN OSUN STATE)', NOW(), NOW()),
  ('Osun State 1', 'Obafemi Awolowo University - IFE', NOW(), NOW()),
  ('Osun State 1', 'Obafemi Awolowo University - PRE-DEGREE', NOW(), NOW()),
  ('Osun State 1', 'Obafemi Awolowo University - TEACHING HOSPITAL', NOW(), NOW()),
  ('Osun State 1', 'Oduduwa University - IFE', NOW(), NOW()),
  ('Osun State 1', 'Osun State College Of Education - ESA OKE', NOW(), NOW()),
  ('Osun State 1', 'Osun State College Of Education - ILESHA', NOW(), NOW()),
  ('Osun State 1', 'Osun State College Of Education - ORANGUN', NOW(), NOW()),
  ('Osun State 1', 'Osun State Polytechnic, Iree', NOW(), NOW()),
  ('Osun State 1', 'The Polytechnic, Igbajo, Boluwaduro', NOW(), NOW()),
  ('Osun State 1', 'School Of Nursing - IFE', NOW(), NOW()),
  ('Osun State 1', 'School Of Nursing - OSOGBO', NOW(), NOW()),
  ('Osun State 1', 'Osun State University, EJIGBO', NOW(), NOW()),
  ('Osun State 1', 'Osun State University, IFETEDO', NOW(), NOW()),
  ('Osun State 1', 'Osun State University, IKIRE', NOW(), NOW()),
  ('Osun State 1', 'Osun State University, OKUKU', NOW(), NOW()),
  ('Osun State 2', 'Bowen University, Iwo', NOW(), NOW()),
  ('Osun State 2', 'Federal Polytechnic Ede', NOW(), NOW()),
  ('Osun State 2', 'Foreign Links Polytechnic, Ishasha, Ife North', NOW(), NOW()),
  ('Osun State 2', 'Ife Polytechnic', NOW(), NOW()),
  ('Osun State 2', 'Interlinks Polytechnic', NOW(), NOW()),
  ('Osun State 2', 'Joseph Ayo Babalola University', NOW(), NOW()),
  ('Osun State 2', 'Ladoke Akintola University Of Technology - TEACHING HOSPITAL, Osogbo', NOW(), NOW()),
  ('Osun State 2', 'Living Spring College of Technology, Osogbo', NOW(), NOW()),
  ('Osun State 2', 'National Open University of Nigeria (ALL CAMPUSES IN OSUN STATE)', NOW(), NOW()),
  ('Osun State 2', 'Obafemi Awolowo University - IFE', NOW(), NOW()),
  ('Osun State 2', 'Obafemi Awolowo University - PRE-DEGREE', NOW(), NOW()),
  ('Osun State 2', 'Obafemi Awolowo University - TEACHING HOSPITAL', NOW(), NOW()),
  ('Osun State 2', 'Oduduwa University - IFE', NOW(), NOW()),
  ('Osun State 2', 'Osun State College Of Education - ESA OKE', NOW(), NOW()),
  ('Osun State 2', 'Osun State College Of Education - ILESHA', NOW(), NOW()),
  ('Osun State 2', 'Osun State College Of Education - ORANGUN', NOW(), NOW()),
  ('Osun State 2', 'Osun State Polytechnic, Iree', NOW(), NOW()),
  ('Osun State 2', 'The Polytechnic, Igbajo, Boluwaduro', NOW(), NOW()),
  ('Osun State 2', 'School Of Nursing - IFE', NOW(), NOW()),
  ('Osun State 2', 'School Of Nursing - OSOGBO', NOW(), NOW()),
  ('Osun State 2', 'Osun State University, EJIGBO', NOW(), NOW()),
  ('Osun State 2', 'Osun State University, IFETEDO', NOW(), NOW()),
  ('Osun State 2', 'Osun State University, IKIRE', NOW(), NOW()),
  ('Osun State 2', 'Osun State University, OKUKU', NOW(), NOW()),
  ('Oyo State (Central)', 'Others not listed', NOW(), NOW()),
  ('Oyo State (Central)', 'Aquatech College of Agriculture and Technology, Fodasi, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Ajayi Crowther University, Oyo', NOW(), NOW()),
  ('Oyo State (Central)', 'Best Legacy College Of Education, Ogbomosho', NOW(), NOW()),
  ('Oyo State (Central)', 'Bowen Teaching Hospital, Ogbomosho', NOW(), NOW()),
  ('Oyo State (Central)', 'Catholic Hospital Oluyoro, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Oyo State College Of Agriculture, and Technology, Igbora', NOW(), NOW()),
  ('Oyo State (Central)', 'Delar College Of Education, Egbeda Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Emmanuel Alayande College Of Education, Lanlate', NOW(), NOW()),
  ('Oyo State (Central)', 'Emmanuel Olayande College Of Education, Oyo', NOW(), NOW()),
  ('Oyo State (Central)', 'Federal College Of Forestry, Jericho, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Federal Cooperative College, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Federal School Of Statistics, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Highland College Of Technology, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Institute Of Agricultural Research And Training, IAR&T (FCA, IBADAN; FCAH&PT, IBADAN)', NOW(), NOW()),
  ('Oyo State (Central)', 'Ladoke Akintola University Of Technology, Ogbomosho', NOW(), NOW()),
  ('Oyo State (Central)', 'Lead City University, Oluyole Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'National Open University of Nigeria (CAMPUSES IN OYO STATE), Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'The Okeogun Polytechnic, Saki', NOW(), NOW()),
  ('Oyo State (Central)', 'Oyo State College of Health Science and Tech, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Oyo State College Of Nursing and Midwifrey, Ogbomosho', NOW(), NOW()),
  ('Oyo State (Central)', 'Oyo State College Of Nursing and Midwifrey, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Oyo State College Of Nursing, Medical Laboratory And Midwifery, Ogbomosho', NOW(), NOW()),
  ('Oyo State (Central)', 'Federal School Of Survey, Oyo', NOW(), NOW()),
  ('Oyo State (Central)', 'The Polytechnic Ibadan, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'The Ibarapa Polytechnic, Eruwa, Ibarapa', NOW(), NOW()),
  ('Oyo State (Central)', 'Tower Polytechnic, Ire Akari, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'University Of Ibadan, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'University College Hospital (UCH), Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Federal College of Education (Sp), Oyo', NOW(), NOW()),
  ('Oyo State (Central)', 'Baptist School of Nursing, Saki', NOW(), NOW()),
  ('Oyo State (Central)', 'Baptist School of Medical Laboratory, Saki', NOW(), NOW()),
  ('Oyo State (Central)', 'Oyo state School of Midwifery, Kishi', NOW(), NOW()),
  ('Oyo State (Central)', 'KolaDaisi, University, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Cornerstone University, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'First Technical University, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Ibadan City Polytechnic, Ibadan', NOW(), NOW()),
  ('Oyo State (Central)', 'Federal University of Agriculture and Technology, Okeho', NOW(), NOW()),
  ('Oyo State (North)', 'Others not listed', NOW(), NOW()),
  ('Oyo State (North)', 'Aquatech College of Agriculture and Technology, Fodasi, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Ajayi Crowther University, Oyo', NOW(), NOW()),
  ('Oyo State (North)', 'Best Legacy College Of Education, Ogbomosho', NOW(), NOW()),
  ('Oyo State (North)', 'Bowen Teaching Hospital, Ogbomosho', NOW(), NOW()),
  ('Oyo State (North)', 'Catholic Hospital Oluyoro, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Oyo State College Of Agriculture, and Technology, Igbora', NOW(), NOW()),
  ('Oyo State (North)', 'Delar College Of Education, Egbeda Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Emmanuel Alayande College Of Education, Lanlate', NOW(), NOW()),
  ('Oyo State (North)', 'Emmanuel Olayande College Of Education, Oyo', NOW(), NOW()),
  ('Oyo State (North)', 'Federal College Of Forestry, Jericho, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Federal Cooperative College, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Federal School Of Statistics, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Highland College Of Technology, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Institute Of Agricultural Research And Training, IAR&T (FCA, IBADAN; FCAH&PT, IBADAN)', NOW(), NOW()),
  ('Oyo State (North)', 'Ladoke Akintola University Of Technology, Ogbomosho', NOW(), NOW()),
  ('Oyo State (North)', 'Lead City University, Oluyole Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'National Open University of Nigeria (CAMPUSES IN OYO STATE), Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'The Okeogun Polytechnic, Saki', NOW(), NOW()),
  ('Oyo State (North)', 'Oyo State College of Health Science and Tech, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Oyo State College Of Nursing and Midwifrey, Ogbomosho', NOW(), NOW()),
  ('Oyo State (North)', 'Oyo State College Of Nursing and Midwifrey, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Oyo State College Of Nursing, Medical Laboratory And Midwifery, Ogbomosho', NOW(), NOW()),
  ('Oyo State (North)', 'Federal School Of Survey, Oyo', NOW(), NOW()),
  ('Oyo State (North)', 'The Polytechnic Ibadan, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'The Ibarapa Polytechnic, Eruwa, Ibarapa', NOW(), NOW()),
  ('Oyo State (North)', 'Tower Polytechnic, Ire Akari, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'University Of Ibadan, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'University College Hospital (UCH), Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Federal College of Education (Sp), Oyo', NOW(), NOW()),
  ('Oyo State (North)', 'Baptist School of Nursing, Saki', NOW(), NOW()),
  ('Oyo State (North)', 'Baptist School of Medical Laboratory, Saki', NOW(), NOW()),
  ('Oyo State (North)', 'Oyo state School of Midwifery, Kishi', NOW(), NOW()),
  ('Oyo State (North)', 'KolaDaisi, University, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Cornerstone University, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'First Technical University, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Ibadan City Polytechnic, Ibadan', NOW(), NOW()),
  ('Oyo State (North)', 'Federal University of Agriculture and Technology, Okeho', NOW(), NOW()),
  ('Oyo State (South)', 'Others not listed', NOW(), NOW()),
  ('Oyo State (South)', 'Aquatech College of Agriculture and Technology, Fodasi, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Ajayi Crowther University, Oyo', NOW(), NOW()),
  ('Oyo State (South)', 'Best Legacy College Of Education, Ogbomosho', NOW(), NOW()),
  ('Oyo State (South)', 'Bowen Teaching Hospital, Ogbomosho', NOW(), NOW()),
  ('Oyo State (South)', 'Catholic Hospital Oluyoro, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo State College Of Agriculture, and Technology, Igbora', NOW(), NOW()),
  ('Oyo State (South)', 'Delar College Of Education, Egbeda Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Emmanuel Alayande College Of Education, Lanlate', NOW(), NOW()),
  ('Oyo State (South)', 'Emmanuel Olayande College Of Education, Oyo', NOW(), NOW()),
  ('Oyo State (South)', 'Federal College Of Forestry, Jericho, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Federal Cooperative College, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Federal School Of Statistics, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Highland College Of Technology, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Institute Of Agricultural Research And Training, IAR&T (FCA, IBADAN; FCAH&PT, IBADAN)', NOW(), NOW()),
  ('Oyo State (South)', 'Ladoke Akintola University Of Technology, Ogbomosho', NOW(), NOW()),
  ('Oyo State (South)', 'Lead City University, Oluyole Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'National Open University of Nigeria (CAMPUSES IN OYO STATE), Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'The Okeogun Polytechnic, Saki', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo State College of Health Science and Tech, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo State College Of Nursing and Midwifrey, Ogbomosho', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo State College Of Nursing and Midwifrey, Eleyele, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo State College Of Nursing, Medical Laboratory And Midwifery, Ogbomosho', NOW(), NOW()),
  ('Oyo State (South)', 'Federal School Of Survey, Oyo', NOW(), NOW()),
  ('Oyo State (South)', 'The Polytechnic Ibadan, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'The Ibarapa Polytechnic, Eruwa, Ibarapa', NOW(), NOW()),
  ('Oyo State (South)', 'Tower Polytechnic, Ire Akari, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'University Of Ibadan, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'University College Hospital (UCH), Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Federal College of Education (Sp), Oyo', NOW(), NOW()),
  ('Oyo State (South)', 'Baptist School of Nursing, Saki', NOW(), NOW()),
  ('Oyo State (South)', 'Baptist School of Medical Laboratory, Saki', NOW(), NOW()),
  ('Oyo State (South)', 'Oyo state School of Midwifery, Kishi', NOW(), NOW()),
  ('Oyo State (South)', 'KolaDaisi, University, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Cornerstone University, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'First Technical University, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Ibadan City Polytechnic, Ibadan', NOW(), NOW()),
  ('Oyo State (South)', 'Federal University of Agriculture and Technology, Okeho', NOW(), NOW());
