INSERT INTO fellowship_centres (name, state, region, created_at, updated_at)
VALUES
('DLCF His Presence Center Afijio', 'Oyo', 'Afijio', NOW(), NOW()),
('DLCF Jubilee Center Afijio', 'Oyo', 'Afijio', NOW(), NOW()),
('DLCF Lords Center Afijio', 'Oyo', 'Afijio', NOW(), NOW()),
('DLCF Saviour Center Afijio', 'Oyo', 'Afijio', NOW(), NOW()),
('DLCF Zion Center Afijio', 'Oyo', 'Afijio', NOW(), NOW()),
('DLCF Ajoda Centre Egbeda', 'Oyo', 'Egbeda', NOW(), NOW()),
('DLCF Hallelujah Centre Egbeda', 'Oyo', 'Egbeda', NOW(), NOW()),
('DLCF Agape Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Agbowo Peace Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Agbowo Progress Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Anchor Centre Apete, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Aquatech Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Benjamin Centre, Eleyele, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Conerstone Centre Apete, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Corpers Church, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Dominion Centre Apete, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Emmanuel Centre', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Federal College of Forestry Centre, Jericho, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Federal Cooperative College Centre, Eleyele, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Federal Training School, UCH, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Grace Centre Apete, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Hephziphah, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Highland College of Technology Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF IAR&T Bora Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF IAR&T Life care Centre (Adabeji), Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Ibadan City Poly, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Imperial Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Milestone Centre Apete, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF OYSCOHTECH Centre, Eleyele, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Oyo State College of Nursing and Midwifery, Eleyele, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Poly North, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Poly Off-Campus, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Poly South, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Poly Unity Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Recovery Centre Apete, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF School of Midwifery, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Trioses/NOUN Centre, Sango, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UCH Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Abadina Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Agbowo Purity Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Ajibode Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Awo Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Indy Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Kuti Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Mellamby Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF UI Zik Centre, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF, Catholic Hospital Centre, Oluyoro, Ibadan', 'Oyo', 'Ibadan', NOW(), NOW()),
('DLCF Adeseun Ogundoyin Polytechnic, Eruwa-Ibarapa', 'Oyo', 'Ibarapa', NOW(), NOW()),
('DLCF Oyo State College of Education, Lanlate-Ibarapa', 'Oyo', 'Ibarapa', NOW(), NOW()),
('Mount Zion Centre, Ido', 'Oyo', 'Ido', NOW(), NOW()),
('Rehoboth centre, Ido', 'Oyo', 'Ido', NOW(), NOW()),
('DLCF Corper Iseyin', 'Oyo', 'Iseyin', NOW(), NOW()),
('DLCF SAF Poly Odomu-Iseyin', 'Oyo', 'Iseyin', NOW(), NOW()),
('Bethel Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Camp Zion Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Canaan Land Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('General Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Glory Land Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Higher Ground Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('LTH Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Lecture Hall Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Mount Zion Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Olukoko Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('Peculiar Center, Ogbomoso', 'Oyo', 'Ogbomosho', NOW(), NOW()),
('DLCF First Technical University Oluyole', 'Oyo', 'Oluyole', NOW(), NOW()),
('DLCF Lead City University Centre Felele Oluyole', 'Oyo', 'Oluyole', NOW(), NOW()),
('DLCF Lead City University main campus Centre Oluyole', 'Oyo', 'Oluyole', NOW(), NOW()),
('Canaan Land Centre', 'Oyo', 'Oyo', NOW(), NOW()),
('Federal School of Surveying(FSS)', 'Oyo', 'Oyo', NOW(), NOW()),
('Promised Land Centre', 'Oyo', 'Oyo', NOW(), NOW()),
('Wisdom Centre', 'Oyo', 'Oyo', NOW(), NOW()),
('Faith Centre Saki', 'Oyo', 'Saki', NOW(), NOW()),
('Irewole Centre, Saki', 'Oyo', 'Saki', NOW(), NOW()),
('Victory Centre Apinnite, Saki', 'Oyo', 'Saki', NOW(), NOW()),
('DLCF Millenium', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF National Open University', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF UNIMED, Akure', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF Zion Center Afijio', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Alejolowo', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Apatapiti', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Corpers  Church', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Footprint', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Health Technology', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Ibule', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, North Gate', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF, Postgraduate/Staff', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF,AAUA, Ero Camous', 'Ondo North', 'Akure', NOW(), NOW()),
('DLCF Corpers Church', 'Ondo North', 'Akure North', NOW(), NOW()),
('DLCF East Campus', 'Ondo North', 'Akure North', NOW(), NOW()),
('DLCF West Campus', 'Ondo North', 'Akure North', NOW(), NOW()),
('Success Arena, Eshe', 'Ondo North', 'Ikare', NOW(), NOW()),
('DLCF Blessed Arena', 'Ondo North', 'Oka', NOW(), NOW()),
('DLCF Dominion Arena', 'Ondo North', 'Oka', NOW(), NOW()),
('DLCF Life Arena', 'Ondo North', 'Oka', NOW(), NOW()),
('DLCF Testimony Arena', 'Ondo North', 'Oka', NOW(), NOW()),
('DLCF Wisdom Arena', 'Ondo North', 'Oka', NOW(), NOW()),
('DLCF Blessed Arena', 'Ondo North', 'Owo', NOW(), NOW()),
('DLCF Dominion Arena', 'Ondo North', 'Owo', NOW(), NOW()),
('DLCF Life Arena', 'Ondo North', 'Owo', NOW(), NOW()),
('DLCF Testimony Arena', 'Ondo North', 'Owo', NOW(), NOW()),
('DLCF Wisdom Arena', 'Ondo North', 'Owo', NOW(), NOW()),
('DLCF Oke Alaafia', 'Ondo South', 'ILE OLUJI', NOW(), NOW()),
('DLCF Corpers', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Fiwasaye', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Laje', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Main campus', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Odosida', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Oka', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Second gate', 'Ondo South', 'ONDO', NOW(), NOW()),
('DLCF Wing C', 'Ondo South', 'ONDO', NOW(), NOW());
