INSERT INTO fellowship_centres (name, state, region, created_at, updated_at)
VALUES
('DLCF His Presence Center Afijio', 'Oyo State (South)', 'Afijio', NOW(), NOW()),
('DLCF Jubilee Center Afijio', 'Oyo State (South)', 'Afijio', NOW(), NOW()),
('DLCF Lords Center Afijio', 'Oyo State (South)', 'Afijio', NOW(), NOW()),
('DLCF Saviour Center Afijio', 'Oyo State (South)', 'Afijio', NOW(), NOW()),
('DLCF Zion Center Afijio', 'Oyo State (South)', 'Afijio', NOW(), NOW()),
('DLCF Ajoda Centre Egbeda', 'Oyo State (Central)', 'Egbeda', NOW(), NOW()),
('DLCF Hallelujah Centre Egbeda', 'Oyo State (Central)', 'Egbeda', NOW(), NOW()),
('DLCF Agape Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Agbowo Peace Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Agbowo Progress Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Anchor Centre Apete, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Aquatech Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Benjamin Centre, Eleyele, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Conerstone Centre Apete, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Corpers Church, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Dominion Centre Apete, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Emmanuel Centre', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Federal College of Forestry Centre, Jericho, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Federal Cooperative College Centre, Eleyele, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Federal Training School, UCH, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Grace Centre Apete, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Hephziphah, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Highland College of Technology Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF IAR&T Bora Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF IAR&T Life care Centre (Adabeji), Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Ibadan City Poly, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Imperial Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Milestone Centre Apete, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF OYSCOHTECH Centre, Eleyele, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Oyo State College of Nursing and Midwifery, Eleyele, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Poly North, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Poly Off-Campus, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Poly South, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Poly Unity Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Recovery Centre Apete, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF School of Midwifery, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Trioses/NOUN Centre, Sango, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UCH Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Abadina Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Agbowo Purity Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Ajibode Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Awo Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Indy Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Kuti Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Mellamby Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF UI Zik Centre, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF, Catholic Hospital Centre, Oluyoro, Ibadan', 'Oyo State (Central)', 'Ibadan', NOW(), NOW()),
('DLCF Adeseun Ogundoyin Polytechnic, Eruwa-Ibarapa', 'Oyo State', 'Ibarapa', NOW(), NOW()),
('DLCF Oyo State College of Education, Lanlate-Ibarapa', 'Oyo State', 'Ibarapa', NOW(), NOW()),
('DLCF Mount Zion Centre, Omi-Adio, Ido', 'Oyo State (Central)', 'Ido', NOW(), NOW()),
('DLCF Rehoboth centre,  Abela, Ido', 'Oyo State (Central)', 'Ido', NOW(), NOW()),
('DLCF Corper Iseyin', 'Oyo State', 'Iseyin', NOW(), NOW()),
('DLCF SAF Poly Odomu-Iseyin', 'Oyo State', 'Iseyin', NOW(), NOW()),
('DLCF Bethel Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Camp Zion Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Canaan Land Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF General Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Glory Land Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Higher Ground Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF LTH Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Lecture Hall Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Mount Zion Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Olukoko Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF Peculiar Center, Ogbomoso', 'Oyo State (South)', 'Ogbomosho', NOW(), NOW()),
('DLCF First Technical University Oluyole', 'Oyo State (Central)', 'Oluyole', NOW(), NOW()),
('DLCF Lead City University Centre Felele Oluyole', 'Oyo State (Central)', 'Oluyole', NOW(), NOW()),
('DLCF Lead City University main campus Centre Oluyole', 'Oyo State (Central)', 'Oluyole', NOW(), NOW()),
('DLCF Canaan Land Centre', 'Oyo State (South)', 'Oyo', NOW(), NOW()),
('DLCF Federal School of Surveying(FSS)', 'Oyo State (South)', 'Oyo', NOW(), NOW()),
('DLCF Promised Land Centre', 'Oyo State (South)', 'Oyo', NOW(), NOW()),
('DLCF Wisdom Centre', 'Oyo State (South)', 'Oyo', NOW(), NOW()),
('DLCF Faith Centre Saki', 'Oyo', 'Saki', NOW(), NOW()),
('DLCF Irewole Centre, Saki', 'Oyo', 'Saki', NOW(), NOW()),
('DLCF Victory Centre Apinnite, Saki', 'Oyo', 'Saki', NOW(), NOW()),
('DLCF Millenium', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF National Open University', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF UNIMED, Akure', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF Zion Center Afijio', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Alejolowo', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Apatapiti', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Corpers  Church', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Footprint', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Health Technology', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Ibule', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, North Gate', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF, Postgraduate/Staff', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF,AAUA, Ero Camous', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF Corpers Church', 'Ondo State (North)', 'Akure North', NOW(), NOW()),
('DLCF East Campus', 'Ondo State (North)', 'Akure North', NOW(), NOW()),
('DLCF West Campus', 'Ondo State (North)', 'Akure North', NOW(), NOW()),
('DLCF Success Arena, Eshe', 'Ondo State (North)', 'Ikare', NOW(), NOW()),
('DLCF Blessed Arena', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF Dominion Arena', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF Life Arena', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF Testimony Arena', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF Wisdom Arena', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF Blessed Arena', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF Dominion Arena', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF Life Arena', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF Testimony Arena', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF Wisdom Arena', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF, Promised Land location, behind SAF filing Station, beside Chief Olowokere\'s compound, Mini Campus.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF Peace location, Ajebo Junction, Opposite Time Square Hotel, Oru.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF Permanent Site location, Chemical Science Building, Main Campus, Olabisi Onabanjo University.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF Rehoboth location, behind Chips filing station, Chips Junction.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF Mini Campus location, Old Mathematical Science humanities lecture hall 1, mini campus, Olabisi Onabanjo University.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF Power House Lppppocation, pbeside King\'s Gift Secondary School, Koroko, Konigba.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF NOUN location, behind Jesus palace adjacent Alayongbe house, Ijebu.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF Abobi location, adjacent King\'s Gift school, behind mgemo\'s compound.', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF AAP, Ijebu Igbo', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF TASUED,Beautiful Zone Ijele, Ijagun', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF, TASUED, Exploit Zone, Ijagun', 'Ogun State (East)', 'Ijebu-Igbo', NOW(), NOW()),
('DLCF TASUED,Crown of Glory, Imaweje, Ijagun', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF TASUED, Mercy Zone,  Adefisan, Ijebu Ode', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF TASUED,Faith Zone Ososa.', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF TASUED,Able Zone, Ijagun Campus', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF TASUED, Dominion Zone,  Abapawa, Ijagun', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF POGIL College of Health, Ijebu Ode', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF SACOTECH, Omu Campus', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF SACOTECH, Jogbore Campus, Omu-Ajose.', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF OSPOHAS, Zion Location', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF OSPOHAS, Agape Zone, Ijolu Community', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF, Ogun State College of Nursing, Ijebu ode.', 'Ogun State (East)', 'Ijebu-Ode', NOW(), NOW()),
('DLCF OOUTH', 'Ogun State (East)', 'Sagamu', NOW(), NOW()),
('DLCF SOTUBO', 'Ogun State (East)', 'Sagamu', NOW(), NOW()),
('DLCF DL Corpers Felllowship Araromi', 'Ogun State (East)', 'Sagamu', NOW(), NOW()),
('DLCF BU Chapter, Off Olutayo Obadina Rabiu, Behind New Market, Ilishan-Remo, Iperu', 'Ogun State (East)', 'Iperu', NOW(), NOW()),
('DLCF, Gateway Polytechnic, Sapade, F002 Mass Communication Building, Iperu', 'Ogun State (East)', 'Iperu', NOW(), NOW()),
('DLCF Ogijo, Region Camp Ground Cental Group District, Behind Fola Model School, Ogijo', 'Ogun State (East)', 'Ogijo', NOW(), NOW()),
('DLCF Ijebu Ife Region, Opposite Water Corperation, Ijebu Ife', 'Ogun State (East)', 'Ijebu Ife', NOW(), NOW()),
('DLCF Isolog Centre, Ajuwon', 'Ogun State (East)', 'Ajuwon', NOW(), NOW()),
('DLCF Olambe Centre, Ajuwon', 'Ogun State (East)', 'Ajuwon', NOW(), NOW()),
('DLCF DL Corpers Felllowship Owode', 'Ogun State (East)', 'Owode', NOW(), NOW()),
('DLCF MAIN CAMPUS', 'Ondo State (South)', 'Ondo', NOW(), NOW()),
('DLCF WING C', 'Ondo State (South)', 'Ondo', NOW(), NOW()),
('DLCF 2ND GATE', 'Ondo State (South)', 'Ondo', NOW(), NOW()),
('DLCF ODOSIDA', 'Ondo State (South)', 'Ondo', NOW(), NOW()),
('DLCF LAJE', 'Ondo State (South)', 'Ondo', NOW(), NOW()),
('DLCF CORPER FELLOWSHIP', 'Ondo State (South)', 'Ondo', NOW(), NOW()),
('DLCF OKE ALAFIA', 'Ondo State (South)', 'Ile Oluji', NOW(), NOW()),
('DLCF MESSIAH CENTER', 'Ondo State (South)', 'Ile Oluji', NOW(), NOW()),
('DLCF AYEKA CENTER', 'Ondo State (South)', 'Okitipupa', NOW(), NOW()),
('DLCF IGBODIGO CENTER', 'Ondo State (South)', 'Okitipupa', NOW(), NOW()),
('DLCF NDDC CENTER', 'Ondo State (South)', 'Okitipupa', NOW(), NOW()),
('DLCF HQ, PS CENTER', 'Ondo State (South)', 'Okitipupa', NOW(), NOW()),
('DLCF IGODAN CENTER', 'Ondo State (South)', 'Okitipupa', NOW(), NOW()),
('DLCF (DLBC IGODAN DISTRICT)', 'Ondo State (South)', 'Okitipupa', NOW(), NOW()),
('DLCF HEPZIBAH', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF GRA', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Grace Empire', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Dominion', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Dunamis', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Zion', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Behulah', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF College of Nursing', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF New Era', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Rehoboth', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF -Shao', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Kwarapoly', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Sabo-oke', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF College of Education', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Goshen', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Gloryland', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Sango', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Ajegunle', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Kwasu', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Basin', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Overcomer', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Copers Fellowship', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Living Spring', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF College of Health Sciences', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Agbooba', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF IOT/Jupep', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Amazing Grace', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF Bethel', 'Kwara State', 'Ilorin', NOW(), NOW()),
('DLCF ilemona', 'Kwara State', 'Offa', NOW(), NOW()),
('DLCF Nava base DLCF', 'Kwara State', 'Offa', NOW(), NOW()),
('DLCF Nitel DLCF', 'Kwara State', 'Offa', NOW(), NOW()),
('DLCF Mini campus DLCF', 'Kwara State', 'Offa', NOW(), NOW()),
('DLCF College of health Tech', 'Kwara State', 'Offa', NOW(), NOW()),
('DLCF PS', 'Kwara State', 'Offa', NOW(), NOW()),
('DLCF mercy seat', 'Kwara State', 'Ganmo', NOW(), NOW()),
('DLCF Dlcf Sapati', 'Kwara State', 'Ganmo', NOW(), NOW()),
('DLCF life gate', 'Kwara State', 'Ganmo', NOW(), NOW()),
('DLCF fufu', 'Kwara State', 'Ganmo', NOW(), NOW()),
('DLCF-APATAPITI', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-NORTHGATE', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-WESTGATE', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-ALEJOLOWO', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-IBULE', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-PG-STAFF', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-AKURE-CORPERS', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-AAUA-ERO', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-UNIMED-AKURE', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-MILLENNIUM', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-HEALTH-TECHOLOGY', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-PEACOCK', 'Ondo State (North)', 'Akure', NOW(), NOW()),
('DLCF-FECA EAST', 'Ondo State (North)', 'Akure North', NOW(), NOW()),
('DLCF-FECA WEST', 'Ondo State (North)', 'Akure North', NOW(), NOW()),
('DLCF-AKURE-NORTH-CORPERS', 'Ondo State (North)', 'Akure North', NOW(), NOW()),
('DLCF-LIFE ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-BETHEL ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-BLESSED ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-GATEWAY ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-DOMINION ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-WISDOM ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-TESTIMONY ARENA', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-SAM MARIS UNIVERSITY', 'Ondo State (North)', 'Oka', NOW(), NOW()),
('DLCF-RUGIPO', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF-ACHIEVER', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF-OWO-CORPERS', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF-IKARE', 'Ondo State (North)', 'Owo', NOW(), NOW()),
('DLCF- TRINITY', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-EKSUTH', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-EKSU MAIN', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-SAMCOM', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-IWOROKO', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-UNITY', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-UNIVERSITY GATE', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-D-HEAD', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-FABOTAS', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-CHRIST REIGNETH', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-POLY ANNEX (MAIN)', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-POLY MOUNT ZION', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-POLY ABUJA', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-ABUAD (ONLINE)', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-CORPERS', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-PATHFINDER', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF-POLY SATELITE (MERCYLAND)', 'Ekiti State (North)', 'Ado', NOW(), NOW()),
('DLCF Corpers\' Centre, Alafara', 'Oyo State (Central)', 'Ido', NOW(), NOW()),
('DLCF Grace Centre, Ido', 'Oyo State (Central)', 'Ido', NOW(), NOW());
